MM = 0.1
U = 19*MM
HOLE_SIZE = 14.1*MM
STB_HOLE_DX = 11.9*MM
STB_HOLE_DY = 0.62*MM
STB_HOLE_W = 7.1*MM
STB_HOLD_H = 13.4*MM
SIDE_NOTCH_DX = 15.66*MM
SIDE_NOTCH_DY = 0.9*MM
SIDE_NOTCH_W = 1*MM
SIDE_NOTCH_H = 2.9*MM
BOTT_NOTCH_DX = STB_HOLE_DX
BOTT_NOTCH_DY = 7.37*MM
BOTT_NOTCH_W = 3.1*MM
BOTT_NOTCH_H = 1.3*MM
FRONT_HEIGHT = 15*MM
REAR_HEIGHT = 25*MM
PANEL_TOP_THICKNESS = 1.5*MM
PANEL_BOTTOM_THICKNESS = 1.5*MM
WALL_THICKNESS = 1.5*MM
PLATE_GAP = 1*MM
PLATE_BOLT_DIST = 0.1*MM
PLATE_THICKNESS = 2*MM
HOLDER_THICKNESS = 3*MM
HOLDER_HEIGHT = 3*MM
HOLDER_DIST = 30*MM
PROMICRO_W = 18.4*MM
PROMICRO_H = 34*MM
PROMICRO_T = 2*MM
PROMICRO_Y = 1.5*MM
USB_L = 2*MM
USB_H = 3.1*MM
USB_W = 8.1*MM
TRRS_H = 10*MM
TRRS_W = 6.4*MM
TRRS_T = 6*MM
TRRS_L = 2*MM
TRRS_RADIUS = 3*MM
SPLIT_KEYS = [
    (1, 7),
    (2, 6),
    (3, 6),
    (4, 6),
]
SPLIT_GAP = 1*MM
# SPLIT_WALL_THICKNESS = 1*MM
CORNER_RADIUS = 5*MM
BOLT_OUTER_RADIUS = 4.1*MM
BOLT_HEIGHT = 4*MM
BOLT_HOLE_RADIUS = 1.0*MM
PLATE_HOLE_RADIUS = 1.2*MM